[package]
name    = "shellfn-core"
version = "0.0.1"
authors = ["Marcin Sas-Szymanski <marcin.sas-szymanski@anixe.pl>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"

[dev-dependencies]
shellfn = { path = "../" }
